kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ocp-terraform-pv-claim-CLUSTERID
  annotations:
    volume.beta.kubernetes.io/storage-class: "STORAGE_CLASS_NAME"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: PVC_SIZEGi
