apiVersion: v1
kind: Secret
metadata:
  name: ocp-terraform-secret-CLUSTERID
type: Opaque
data:
  ibm-api-key: 'ibm-cloud-api-key'
  rh_username: 'redhat-subscription-username'
  rh_password: 'redhat-subscription-password'

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ocp-terraform-config-CLUSTERID
data:
  secrets: |
    ocp-secret
